<a href="https://colab.research.google.com/github/Shreyabansal3112/Linear-Regression/blob/main/sec_b_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

from sklearn import linear_model
from sklearn.metrics import mean_squared_error

In [ ]:
x = np.array([2005,2006,2007,2008,2009]).reshape((-1, 1))
y = np.array([35,30,36,55,50])

In [ ]:
rm=linear_model.LinearRegression()

In [ ]:
rm.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
rm.intercept_

-10997.3

In [ ]:
rm.coef_

array([5.5])

In [ ]:
rm.predict(np.array(2020).reshape(1,-1))

array([112.7])

In [ ]:
rm.predict(np.array(2012).reshape(1,-1))

array([68.7])

In [ ]:
rm.predict(np.array(2010).reshape(1,-1))

array([55.7])

In [ ]:
y_p=rm.predict(x)

In [ ]:
mean_squared_error(y,y_p)

30.46